/*
 * Hatchery API
 *
 * Workspace service for launching and interacting with containers.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PayModel struct {

	Name string `json:"name,omitempty"`

	User string `json:"user,omitempty"`

	AwsAccountId string `json:"awsAccountId,omitempty"`

	Region string `json:"region,omitempty"`

	Ecs string `json:"ecs,omitempty"`
}

// AssertPayModelRequired checks if the required fields are not zero-ed
func AssertPayModelRequired(obj PayModel) error {
	return nil
}

// AssertRecursePayModelRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PayModel (e.g. [][]PayModel), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePayModelRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPayModel, ok := obj.(PayModel)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPayModelRequired(aPayModel)
	})
}
