/*
 * Hatchery API
 *
 * Workspace service for launching and interacting with containers.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ContainerStateDetailRunning struct {

	StartedAt string `json:"StartedAt,omitempty"`
}

// AssertContainerStateDetailRunningRequired checks if the required fields are not zero-ed
func AssertContainerStateDetailRunningRequired(obj ContainerStateDetailRunning) error {
	return nil
}

// AssertRecurseContainerStateDetailRunningRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ContainerStateDetailRunning (e.g. [][]ContainerStateDetailRunning), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseContainerStateDetailRunningRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aContainerStateDetailRunning, ok := obj.(ContainerStateDetailRunning)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertContainerStateDetailRunningRequired(aContainerStateDetailRunning)
	})
}
