/*
 * Hatchery API
 *
 * Workspace service for launching and interacting with containers.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ContainerStateDetailWaiting struct {

	Reason string `json:"reason,omitempty"`

	Message string `json:"message,omitempty"`
}

// AssertContainerStateDetailWaitingRequired checks if the required fields are not zero-ed
func AssertContainerStateDetailWaitingRequired(obj ContainerStateDetailWaiting) error {
	return nil
}

// AssertRecurseContainerStateDetailWaitingRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ContainerStateDetailWaiting (e.g. [][]ContainerStateDetailWaiting), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseContainerStateDetailWaitingRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aContainerStateDetailWaiting, ok := obj.(ContainerStateDetailWaiting)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertContainerStateDetailWaitingRequired(aContainerStateDetailWaiting)
	})
}
